### ISSUE TITLE
android does not work

### ISSUE THREAD

**Issue by liu1083947028** [oney/RCTWebRTCDemo#11]
![image](https://cloud.githubusercontent.com/assets/7359403/15498280/991824e0-21d1-11e6-9bb2-e49e0d8ae375.png)
![image](https://cloud.githubusercontent.com/assets/7359403/15498333/d5ff92da-21d1-11e6-9b72-4bbef7a2443f.png)

build success, but does not work. it is a white page.

How can i do it?

thinks

**Comment by ramsestom** [comment]
experienced the same thing. You should actually wait (can take a couple minutes) for the app to appear.

**Comment by liu1083947028** [comment]
It has been resolved.

ues  command  adb reverse tcp:8081 tcp:8081
