### ISSUE TITLE
Switching to back camera doesn't work

### ISSUE THREAD

**Issue by mavenave** [oney/RCTWebRTCDemo#13]
This is on Android 4.4.4

**Comment by mobileDevNativeCross** [comment]
So at this moment Switching to back camera doesn't work?
In my version doesn't work)

**Comment by mobileDevNativeCross** [comment]
@mavenave @oney or maybe we can just create two entities of `<RTCView streamURL={this.state.selfViewSrc} style={{height:(ScreenSize.height-90)/2,width:ScreenSize.height/2-20}}/>`
and on switching just replace one view with another?
But than we need to detect which stream to send to server.
This is a stupid hack but like I'm understand no one dont know how to fix this issue.
Any suggestions?

**Comment by mattwkelly** [comment]
My current hunch is that the old react-native-webrtc used to automatically send a message to the other client telling it that a renegotiation was needed, but now it's not doing that. @mobileDevNativeCross have you made any progress? @oney , @mavenave , any ideas?

**Comment by lmbao** [comment]
Switch camera does not work for me on iOS

**Comment by zxcpoiu** [comment]
fixed in https://github.com/oney/RCTWebRTCDemo/commit/3916930150c61bf2efc3523c223846f8004386ee
