### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by Beingbook** [oney/RCTWebRTCDemo#2]
<img width="651" alt="2015-11-02 5 23 24" src="https://cloud.githubusercontent.com/assets/2682865/10877097/76819312-8186-11e5-80f2-04ea62092a46.png">
As above image, demo doesn't work.
Can I get any solutions for it?

**Comment by oney** [comment]
Just download the codes and test app 5 minutes ago, it worked.
Can you confirm there is no other react native packager running in terminal?

**Comment by Beingbook** [comment]
It does work.
Thank you!

**Comment by oney** [comment]
Good!

**Comment by liu1083947028** [comment]
I have this issue, how can you to solve it?

thanks
