### ISSUE TITLE
Overlay issue in android

### ISSUE THREAD

**Issue by myrace31** [oney/RCTWebRTCDemo#22]
Hello @oney ,

Thanks for great work, I am using demo app and want to show remoteView on selfView , it works fine for all iOS devices but having same css , not working on android devices. 

Using below css code 

```
<RTCView streamURL={this.state.selfViewSrc} style={styles.selfView}/>
          {
            mapHash(this.state.remoteList, function(remote, index) {
              return <RTCView key={index} streamURL={remote} style={styles.remoteView}/>
            })
          }
```
        
css

```
selfView: {
        width: width,
        height: height-80,
        alignSelf: 'center',
        zIndex: 0,
    },
    remoteView: {
        position: 'absolute',
        zIndex: 2,
        marginTop: -120,
        width: 120,
        height: 120,
        left: 0,
        borderWidth: .5,
        alignSelf: 'flex-start',
    },

```
![device-2016-07-22-173305](https://cloud.githubusercontent.com/assets/2367637/17056798/850e9e58-5033-11e6-9510-27e96120aa0d.png)
![screen shot 2016-07-22 at 5 34 54 pm](https://cloud.githubusercontent.com/assets/2367637/17056799/8518453e-5033-11e6-99f7-9d1da186c451.png)
please suggest me to show view as iOS for android devices.

**Comment by chindanai** [comment]
How do yo fix it?
