### ISSUE TITLE
libjingle_peerconnection build error

### ISSUE THREAD

**Issue by Elqul** [oney/RCTWebRTCDemo#29]
Hello,

this is the error am getting on Android.

```
Error:Execution failed for task ':react-native-webrtc:transformNative_libsWithSyncJniLibsForRelease'.
> java.io.FileNotFoundException: /Users/test/Documents/jitsi-meet/node_modules/react-native-webrtc/android/build/intermediates/bundles/release/jni/lib/x86_64/libjingle_peerconnection_so.so (No such file or directory)
```

how to fix this ?

**Comment by zxcpoiu** [comment]
This seems a gradle issue.

please upgrade your `gradle plugin` in your build.gradle like `com.android.tools.build:gradle:2.2.0`

see:
https://github.com/oney/react-native-webrtc/issues/149#issuecomment-255791200
