### ISSUE TITLE
Build failed with react-native run-android

### ISSUE THREAD

**Issue by wandonye** [oney/RCTWebRTCDemo#32]
> Building and installing the app on the device (cd android && ./gradlew installDebug...
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':WebRTCModule'.
> > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED

Is there anything else should be done but not mentioned in Readme?

**Comment by wandonye** [comment]
It turns out that I downloaded an old version by accident...

**Comment by zxcpoiu** [comment]
thanks for post back your solution
