### ISSUE TITLE
App crashed. Not working on Android 4.2.2 & 4.4.4

### ISSUE THREAD

**Issue by snsekar** [oney/RCTWebRTCDemo#36]
Hi,
I request the authors/contributors to add supported versions on both platforms Android/IOS
I tested on Android 4.2.2 & 4.4.4. Simply app crashed while opening

**Comment by snsekar** [comment]
Found the issue. In AndroidManifest.xml following permission required for Android 4.2.2 & 4.4.4

>     <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

After adding this permission working fine

**Comment by snsekar** [comment]
https://github.com/oney/react-native-webrtc/issues/142

**Comment by zxcpoiu** [comment]
Thanks
I had updated documents: 944bca522c3ccbc33c46c8995d8d04f4e2e0de51
