### ISSUE TITLE
Grey screen when switch camera on android

### ISSUE THREAD

**Issue by Kritcho** [oney/RCTWebRTCDemo#37]
Hi,
When i try to switch camera on android 
In CameraEventsHandler.java will return 
"CameraEventsHandler.onFirstFrameAvailable" (onCameraClosed)
"CameraEventsHandler.onCameraError: errorDescription=Camera can not be started."
 
 Can you please help with it?

**Comment by zxcpoiu** [comment]
Hi @Kritcho 
Is it a permission issue?
Would you mind sharing your solutions which may help others?
Thanks

**Comment by Kritcho** [comment]
Hi @zxcpoiu 
For this solutions I add `videoSource.stop();` when getUserMedia it work for switch camera, 
but don't work when refresh app again.
