### ISSUE TITLE
ios   build  failed

### ISSUE THREAD

**Issue by sailei1** [oney/RCTWebRTCDemo#4]
[Uploading 屏幕快照 2015-11-18 下午3.51.32.png…]

xcode 6.3.1     build  Failed

**Comment by sailei1** [comment]
<img width="968" alt="2015-11-18 3 58 30" src="https://cloud.githubusercontent.com/assets/1625409/11235615/e1e2342a-8e0d-11e5-8058-3e7d8742c971.png">

**Comment by oney** [comment]
Do you solve your problem?

**Comment by sailei1** [comment]
yes  
<img width="233" alt="2015-11-19 9 05 14" src="https://cloud.githubusercontent.com/assets/1625409/11259458/b011c30e-8e9c-11e5-90de-575a7af5d202.png">
