### ISSUE TITLE
Unable to run the demo iOS app on device

### ISSUE THREAD

**Issue by payalbaldota** [oney/RCTWebRTCDemo#43]
![img_3249](https://cloud.githubusercontent.com/assets/3263230/22200251/5a71eb72-e184-11e6-85ec-28eb9d510b25.PNG)
I am getting above error when i run the demo iOS project. 
My configurations are:
"react": "^15.4.2",
 "react-native": "^0.40.0",
 "react-native-webrtc": "git+https://git@github.com/oney/react-native-webrtc.git",
 "socket.io-client": "^1.3.7"
I have already tried the solution mentioned here. https://github.com/facebook/react-native/issues/4968.
but still the error persists

**Comment by payalbaldota** [comment]
Upgrading react-native version to 0.40.0 solved the issue. Also I changed the import statement for sokcet.io in main .js file.
Following are the steps to solve the build errors.

    Clone/Download repository
    hit npm install on root folder from terminal
    hit react-native-git-upgrade on root folder
    hit rm -rf node_modules
    hit watchman watch-del-all
    Change import statement "import io from 'socket.io-client/socket.io';" in main.js to "import io from 'socket.io-client/dist/socket.io';"
    hit npm install on root folder from terminal

Now you can run the demo iOS project with few signing related changes.
Forked working copy https://github.com/payalbaldota/RCTWebRTCDemo

**Comment by zxcpoiu** [comment]
thanks for sharing
