### ISSUE TITLE
Unable to run the demo on iOS simulator

### ISSUE THREAD

**Issue by marclundgren** [oney/RCTWebRTCDemo#5]
Hi @oney,

So, I ran `npm install` from the root, and `npm start` with no problems.

When running the xcode project, I see the following runtime error, which prevents me from seeing the webRTC demo:

<img width="1380" alt="screen shot 2015-12-28 at 12 07 41 pm" src="https://cloud.githubusercontent.com/assets/1154834/12024715/d4fd6f6e-ad5b-11e5-9c08-2d5f78eee70a.png">

**Comment by oney** [comment]
Oh, sorry. Never use simulator to test anything about camera. I will mention it in README.

**Comment by marclundgren** [comment]
Oh, gotcha. Thanks for clearing that up :)
