### ISSUE TITLE
Crash in android 7.0

### ISSUE THREAD

**Issue by swaroopa94** [oney/RCTWebRTCDemo#51]
Hi,

In android 7.0 my app getting crash immediately after entering into the room
It showing an error as shown in below screenshot:

![screen shot 2017-04-18 at 2 25 17 pm](https://cloud.githubusercontent.com/assets/19324363/25123044/ad4ae99a-2444-11e7-9249-e4ac13a0ceab.png)

Please tell me how to resolve it.
Thank you

**Comment by zxcpoiu** [comment]
this probably not thing to do with RCTWebRTCDemo.

the error message tells you clearly that you are trying to unregister a not-registerd receiver.
