### ISSUE TITLE
[Help]: How have you deployed this project on Herokuapp ?

### ISSUE THREAD

**Issue by geekrishabh** [oney/RCTWebRTCDemo#63]
Please Provide me with link/steps to do it.

**Comment by adamcopley** [comment]
quite easy - setup a new app on heroku - the instructions are on the site.

deploy this app: https://github.com/oney/react-native-webrtc-server and NOT the one in this repository

When you have setup said app, go to the "deploy" tab.

Instructions are on that page on how to deploy using git.

Remove the package-lock.json file (as the current one is out of date, and also update the node version within the "engines" section of package.json to a newer version. and there you are!
