### ISSUE TITLE
Execution failed for task ':WebRTCModule:compileReleaseJavaWithJavac'

### ISSUE THREAD

**Issue by EasonWang01** [oney/RCTWebRTCDemo#71]
I saw the previous issue already, but this still happens.

```
"react": "16.0.0-alpha.6",
"react-native": "^0.44.0",
"react-native-webrtc": "git+https://git@github.com/oney/react-native-webrtc.git",
```

1. Add java8 in build.gradle

```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

2.Add jack
```
 jackOptions {
      enabled true
 }
```

then same error again `Execution failed for task ':WebRTCModule:compileReleaseJavaWithJavac'.`

**Comment by ddaaggeett** [comment]
i'm still having this issue as well. did you find a fix? why the `close`?

**Comment by EasonWang01** [comment]
I have created a success build demo, feel free to take a look.
https://github.com/EasonWang01/React-Native-WebRTC
