### ISSUE TITLE
JSON value '0' of type NSNumber cannot be converted to NSArray

### ISSUE THREAD

**Issue by MaartenPI** [oney/RCTWebRTCDemo#8]
Hi Howard,

I get this error: "JSON value '0' of type NSNumber cannot be converted to NSArray", when running the demo from a clean install. 

I'm testing the grounds with iOS-development and don't know how to fix this yet. Do you know what's going on?

Maarten

**Comment by MaartenPI** [comment]
@oney, would you be open to help out with a current webrtc-project? I've been trying some solutions out, but could use some help. If you're up for it, let me know.

**Comment by oney** [comment]
Do you run on real device?

**Comment by MaartenPI** [comment]
I tried the iOS-simulator and a real device. Both gave the same error.

**Comment by oney** [comment]
It is super weird...
Did the error show with red screen on screen or cause the crash?

**Comment by MaartenPI** [comment]
I got it working now, by just starting fresh and following the demo. I think I placed the source files in the wrong folder...

Thx btw for making webrtc easy to use on react native ;)

**Comment by oney** [comment]
:smile:
